package filkomtravel;
// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
//  */
// package filkomtravel;

// /**
//  *
//  * @author rafia
//  */
// public class GAJADI extends javax.swing.JFrame {

//     /**
//      * Creates new form SupirTravel
//      */
//     public GAJADI() {
//         initComponents();
//         data = new Database();
//     }
//     public GAJADI(Database data){
//         this.data= data;
//         initComponents();
//     }
//     public Database data;

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jPanel1 = new javax.swing.JPanel();
//         jLabel1 = new javax.swing.JLabel();
//         jPanel2 = new javax.swing.JPanel();
//         jButton1 = new javax.swing.JButton();
//         jLabel2 = new javax.swing.JLabel();
//         jLabel3 = new javax.swing.JLabel();
//         jTextField1 = new javax.swing.JTextField();
//         jTextField2 = new javax.swing.JTextField();
//         jTextField3 = new javax.swing.JTextField();
//         jTextField4 = new javax.swing.JTextField();
//         jTextField5 = new javax.swing.JTextField();
//         jTextField6 = new javax.swing.JTextField();
//         jLabel4 = new javax.swing.JLabel();
//         jLabel5 = new javax.swing.JLabel();
//         jLabel6 = new javax.swing.JLabel();
//         jLabel7 = new javax.swing.JLabel();
//         jLabel8 = new javax.swing.JLabel();
//         jPanel4 = new javax.swing.JPanel();
//         jButton2 = new javax.swing.JButton();
//         jLabel10 = new javax.swing.JLabel();
//         jLabel11 = new javax.swing.JLabel();
//         jTextField7 = new javax.swing.JTextField();
//         jTextField8 = new javax.swing.JTextField();
//         jTextField11 = new javax.swing.JTextField();
//         jTextField12 = new javax.swing.JTextField();
//         jLabel12 = new javax.swing.JLabel();
//         jLabel14 = new javax.swing.JLabel();
//         jLabel15 = new javax.swing.JLabel();
//         jLabel16 = new javax.swing.JLabel();
//         jLabel17 = new javax.swing.JLabel();
//         jTextField13 = new javax.swing.JTextField();
//         jLabel18 = new javax.swing.JLabel();
//         jComboBox1 = new javax.swing.JComboBox<>();
//         jComboBox2 = new javax.swing.JComboBox<>();
//         jLabel19 = new javax.swing.JLabel();
//         jLabel20 = new javax.swing.JLabel();
//         jTextField14 = new javax.swing.JTextField();
//         jLabel13 = new javax.swing.JLabel();
//         jTextField9 = new javax.swing.JTextField();
//         jTextField15 = new javax.swing.JTextField();
//         jTextField16 = new javax.swing.JTextField();
//         jLabel22 = new javax.swing.JLabel();
//         jLabel23 = new javax.swing.JLabel();
//         jLabel9 = new javax.swing.JLabel();

//         jPanel1.setBackground(new java.awt.Color(102, 102, 255));

//         jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
//         jLabel1.setText("FILKOM TRAVEL");

//         javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//         jPanel1.setLayout(jPanel1Layout);
//         jPanel1Layout.setHorizontalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addComponent(jLabel1)
//                 .addGap(466, 466, 466))
//         );
//         jPanel1Layout.setVerticalGroup(
//             jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
//                 .addContainerGap(44, Short.MAX_VALUE)
//                 .addComponent(jLabel1)
//                 .addGap(40, 40, 40))
//         );

//         jPanel2.setBackground(new java.awt.Color(204, 204, 255));

//         jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
//         jButton1.setText("PESAN");
//         jButton1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton1ActionPerformed(evt);
//             }
//         });

//         jLabel2.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//         jLabel2.setText("DATA PESANAN");
//         jLabel2.setEnabled(false);

//         jLabel3.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel3.setText("NAMA :");

//         jTextField1.setText("jTextField1");
//         jTextField1.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField1ActionPerformed(evt);
//             }
//         });

//         jTextField2.setText("jTextField1");
//         jTextField2.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField2ActionPerformed(evt);
//             }
//         });

//         jTextField3.setText("jTextField1");
//         jTextField3.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField3ActionPerformed(evt);
//             }
//         });

//         jTextField4.setText("jTextField1");
//         jTextField4.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField4ActionPerformed(evt);
//             }
//         });

//         jTextField5.setText("jTextField1");
//         jTextField5.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField5ActionPerformed(evt);
//             }
//         });

//         jTextField6.setText("jTextField1");
//         jTextField6.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField6ActionPerformed(evt);
//             }
//         });

//         jLabel4.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel4.setText("NAMA :");

//         jLabel5.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel5.setText("NAMA :");

//         jLabel6.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel6.setText("NAMA :");

//         jLabel7.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel7.setText("NAMA :");

//         jLabel8.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel8.setText("NAMA :");

//         javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//         jPanel2.setLayout(jPanel2Layout);
//         jPanel2Layout.setHorizontalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                         .addComponent(jLabel2)
//                         .addGap(496, 496, 496))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                         .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(507, 507, 507))))
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addGap(190, 190, 190)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addGroup(jPanel2Layout.createSequentialGroup()
//                         .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel2Layout.createSequentialGroup()
//                         .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(18, 18, 18)
//                         .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel2Layout.createSequentialGroup()
//                         .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel2Layout.createSequentialGroup()
//                         .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel2Layout.createSequentialGroup()
//                         .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(18, 18, 18)
//                         .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
//                 .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(18, 18, 18)
//                 .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(287, 287, 287))
//         );
//         jPanel2Layout.setVerticalGroup(
//             jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel2Layout.createSequentialGroup()
//                 .addGap(28, 28, 28)
//                 .addComponent(jLabel2)
//                 .addGap(70, 70, 70)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(18, 18, 18)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(18, 18, 18)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(18, 18, 18)
//                 .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
//                 .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(35, 35, 35))
//         );

//         setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

//         jPanel4.setBackground(new java.awt.Color(204, 204, 255));

//         jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
//         jButton2.setText("SUBMIT");
//         jButton2.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jButton2ActionPerformed(evt);
//             }
//         });

//         jLabel10.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//         jLabel10.setText("Supir Travel");
//         jLabel10.setEnabled(false);

//         jLabel11.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel11.setText("NO TELP :");

//         jTextField7.setText("jTextField1");
//         jTextField7.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField7ActionPerformed(evt);
//             }
//         });

//         jTextField8.setText("jTextField1");
//         jTextField8.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField8ActionPerformed(evt);
//             }
//         });

//         jTextField11.setText("jTextField1");
//         jTextField11.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField11ActionPerformed(evt);
//             }
//         });

//         jTextField12.setText("jTextField1");
//         jTextField12.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField12ActionPerformed(evt);
//             }
//         });

//         jLabel12.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel12.setText("NAMA:");

//         jLabel14.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel14.setText("UMUR :");

//         jLabel15.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel15.setText("JENIS KELAMIN :");

//         jLabel16.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel16.setText("ALAMAT :");

//         jLabel17.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel17.setText("NIK :");

//         jTextField13.setText("jTextField1");
//         jTextField13.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField13ActionPerformed(evt);
//             }
//         });

//         jLabel18.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel18.setText("RUTE :");

//         jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perrempuan" }));

//         jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Surabaya-Malang", "Madura-Malang", "Banyuwangi-Malang", "Situbondo-Malang", "Tulungagung-Malang" }));
//         jComboBox2.setToolTipText("");

//         jLabel19.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel19.setText("MERK :");

//         jLabel20.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel20.setText("TAHUN :");

//         jTextField14.setText("jTextField1");
//         jTextField14.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField14ActionPerformed(evt);
//             }
//         });

//         jLabel13.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel13.setText("NO PLAT :");

//         jTextField9.setText("jTextField1");
//         jTextField9.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField9ActionPerformed(evt);
//             }
//         });

//         jTextField15.setText("jTextField1");
//         jTextField15.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField15ActionPerformed(evt);
//             }
//         });

//         jTextField16.setText("jTextField1");
//         jTextField16.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 jTextField16ActionPerformed(evt);
//             }
//         });

//         jLabel22.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
//         jLabel22.setText("WARNA");

//         jLabel23.setBackground(new java.awt.Color(255, 255, 255));
//         jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
//         jLabel23.setText("MOBIL");
//         jLabel23.setEnabled(false);

//         jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
//         jLabel9.setText("FILKOM TRAVEL");

//         javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//         jPanel4.setLayout(jPanel4Layout);
//         jPanel4Layout.setHorizontalGroup(
//             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addGap(207, 207, 207)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addGap(60, 60, 60)
//                         .addComponent(jComboBox2, 0, 1, Short.MAX_VALUE))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
//                         .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                 .addGap(92, 92, 92)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                         .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
//                         .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                 .addGap(0, 0, Short.MAX_VALUE)
//                 .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(427, 427, 427))
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addGap(279, 279, 279)
//                 .addComponent(jLabel10)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addComponent(jLabel23)
//                 .addGap(260, 260, 260))
//             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                 .addContainerGap()
//                 .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
//                 .addGap(70, 70, 70))
//         );
//         jPanel4Layout.setVerticalGroup(
//             jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(jPanel4Layout.createSequentialGroup()
//                 .addGap(12, 12, 12)
//                 .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel10)
//                     .addComponent(jLabel23))
//                 .addGap(51, 51, 51)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                     .addGroup(jPanel4Layout.createSequentialGroup()
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(18, 18, 18)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                         .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                             .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
//                             .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addGap(44, 44, 44)))
//                 .addGap(17, 17, 17)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(18, 18, 18)
//                 .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(91, 91, 91))
//         );

//         jTextField7.getAccessibleContext().setAccessibleName("namabox");
//         jTextField8.getAccessibleContext().setAccessibleName("umurbox");
//         jTextField11.getAccessibleContext().setAccessibleName("nobox");
//         jTextField12.getAccessibleContext().setAccessibleName("alamatbox");
//         jTextField13.getAccessibleContext().setAccessibleName("nikbox");
//         jTextField14.getAccessibleContext().setAccessibleName("tahun");
//         jTextField9.getAccessibleContext().setAccessibleName("warnamobilbox");
//         jTextField15.getAccessibleContext().setAccessibleName("plat");
//         jTextField16.getAccessibleContext().setAccessibleName("merkmobilbox");

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//         getContentPane().setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                 .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addContainerGap())
//         );

//         pack();
//     }// </editor-fold>//GEN-END:initComponents

//     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jButton1ActionPerformed

//     private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField1ActionPerformed

//     private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField2ActionPerformed

//     private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField3ActionPerformed

//     private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField4ActionPerformed

//     private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField5ActionPerformed

//     private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField6ActionPerformed

//     private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//     String nama = jTextField7.getText();
//     String alamat = jTextField12.getText();
//     String nomer = jTextField11.getText();
//     String kelamin = jComboBox1.getSelectedItem().toString();
//     String NIK = jTextField13.getText();
//     String umur = jTextField8.getText();
//     String rute = jComboBox2.getSelectedItem().toString();
//     String warna = jTextField9.getText();
//     String merk= jTextField15.getText();
//     String plat = jTextField14.getText();
//     String tahun = jTextField14.getText();
//     }//GEN-LAST:event_jButton2ActionPerformed

//     private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField7ActionPerformed

//     private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField8ActionPerformed

//     private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField11ActionPerformed

//     private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField12ActionPerformed

//     private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField13ActionPerformed

//     private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField14ActionPerformed

//     private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField9ActionPerformed

//     private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField15ActionPerformed

//     private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
//         // TODO add your handling code here:
//     }//GEN-LAST:event_jTextField16ActionPerformed

//     /**
//      * @param args the command line arguments
//      */
//     public static void main(String args[]) {
//         /* Set the Nimbus look and feel */
//         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//         /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//          * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//          */
//         try {
//             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                 if ("Nimbus".equals(info.getName())) {
//                     javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                     break;
//                 }
//             }
//         } catch (ClassNotFoundException ex) {
//             java.util.logging.Logger.getLogger(GAJADI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (InstantiationException ex) {
//             java.util.logging.Logger.getLogger(GAJADI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (IllegalAccessException ex) {
//             java.util.logging.Logger.getLogger(GAJADI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//             java.util.logging.Logger.getLogger(GAJADI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//         }
//         //</editor-fold>

//         /* Create and display the form */
//         java.awt.EventQueue.invokeLater(new Runnable() {
//             public void run() {
//                 new GAJADI().setVisible(true);
//             }
//         });
//     }

//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton jButton1;
//     private javax.swing.JButton jButton2;
//     private javax.swing.JComboBox<String> jComboBox1;
//     private javax.swing.JComboBox<String> jComboBox2;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel10;
//     private javax.swing.JLabel jLabel11;
//     private javax.swing.JLabel jLabel12;
//     private javax.swing.JLabel jLabel13;
//     private javax.swing.JLabel jLabel14;
//     private javax.swing.JLabel jLabel15;
//     private javax.swing.JLabel jLabel16;
//     private javax.swing.JLabel jLabel17;
//     private javax.swing.JLabel jLabel18;
//     private javax.swing.JLabel jLabel19;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JLabel jLabel20;
//     private javax.swing.JLabel jLabel22;
//     private javax.swing.JLabel jLabel23;
//     private javax.swing.JLabel jLabel3;
//     private javax.swing.JLabel jLabel4;
//     private javax.swing.JLabel jLabel5;
//     private javax.swing.JLabel jLabel6;
//     private javax.swing.JLabel jLabel7;
//     private javax.swing.JLabel jLabel8;
//     private javax.swing.JLabel jLabel9;
//     private javax.swing.JPanel jPanel1;
//     private javax.swing.JPanel jPanel2;
//     private javax.swing.JPanel jPanel4;
//     private javax.swing.JTextField jTextField1;
//     private javax.swing.JTextField jTextField11;
//     private javax.swing.JTextField jTextField12;
//     private javax.swing.JTextField jTextField13;
//     private javax.swing.JTextField jTextField14;
//     private javax.swing.JTextField jTextField15;
//     private javax.swing.JTextField jTextField16;
//     private javax.swing.JTextField jTextField2;
//     private javax.swing.JTextField jTextField3;
//     private javax.swing.JTextField jTextField4;
//     private javax.swing.JTextField jTextField5;
//     private javax.swing.JTextField jTextField6;
//     private javax.swing.JTextField jTextField7;
//     private javax.swing.JTextField jTextField8;
//     private javax.swing.JTextField jTextField9;
//     // End of variables declaration//GEN-END:variables
// }
