/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuliah.studycasepbo;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class DetailPemasananTransGui extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    Transportasi bus;
    DatadiriPenumpang data;
    String tanggal;
    String nama;
    String email;
    String no;
    int harga;
    int kursi;
    Akun akun;
    HomeGui home;

    public DetailPemasananTransGui(DatadiriPenumpang data, Transportasi bus, String tanggal, String nama, String email, String no, int kursi, Akun akun, HomeGui home) {
        this.tanggal = tanggal;
        this.data = data;
        this.bus = bus;
        this.nama = nama;
        this.email = email;
        this.no = no;
        this.harga = Integer.parseInt(bus.harga) * kursi;
        this.setVisible(true);
        this.kursi = kursi;
        this.home = home;
        this.akun = akun;
        initComponents();
    }

    String getNama() {
        return nama;
    }

    String getEmail() {
        return email;
    }

    String getNo() {
        return no;
    }

    String getTanggal() {
        return tanggal;
    }

    int getPajak() {
        return harga * 5 / 100;
    }

    int total() {
        return harga + getPajak();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        labelTranspo = new javax.swing.JLabel();
        labelTujuan = new javax.swing.JLabel();
        labelKeberangkatan = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LabelTanggal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelHarga1 = new javax.swing.JLabel();
        labelHarga2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        KembaliButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Keliling");

        jPanel1.setBackground(new java.awt.Color(25, 22, 22));
        jPanel1.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(44, 41, 41));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Detail Pemesanan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 5, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNama.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        labelNama.setForeground(new java.awt.Color(0, 0, 0));
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama.setText("Nama");
        jPanel3.add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        labelTranspo.setBackground(new java.awt.Color(0, 0, 0));
        labelTranspo.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        labelTranspo.setForeground(new java.awt.Color(0, 0, 0));
        labelTranspo.setText("Transportasi");
        jPanel3.add(labelTranspo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        labelTujuan.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        labelTujuan.setForeground(new java.awt.Color(0, 0, 0));
        labelTujuan.setText("Tujuan");
        jPanel3.add(labelTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        labelKeberangkatan.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        labelKeberangkatan.setForeground(new java.awt.Color(0, 0, 0));
        labelKeberangkatan.setText("Keberangkatan");
        jPanel3.add(labelKeberangkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        labelHarga.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        labelHarga.setForeground(new java.awt.Color(0, 0, 0));
        labelHarga.setText("Pajak 5%");
        jPanel3.add(labelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jButton1.setBackground(new java.awt.Color(70, 73, 75));
        jButton1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Bayar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 275, 100, 30));

        LabelTanggal.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        LabelTanggal.setForeground(new java.awt.Color(0, 0, 0));
        LabelTanggal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTanggal.setText("Tanggal");
        jPanel3.add(LabelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 560, 2));

        labelHarga1.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        labelHarga1.setForeground(new java.awt.Color(0, 0, 0));
        labelHarga1.setText("Harga");
        jPanel3.add(labelHarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        labelHarga2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        labelHarga2.setForeground(new java.awt.Color(0, 0, 0));
        labelHarga2.setText("Total");
        jPanel3.add(labelHarga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(getTanggal());
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, 25));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Rp"+total());
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 150, 25));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText(getNama());
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 250, 25));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText(bus.getClass().getSimpleName());
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 150, 25));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText(bus.tujuan);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 250, 25));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText(bus.keberangkatan);
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, 25));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Rp"+harga);
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 150, 25));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Rp"+getPajak());
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 150, 25));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 620, 320));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 620, 360));

        jLabel1.setFont(new java.awt.Font("Montserrat Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pembayaran");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        KembaliButton.setBackground(new java.awt.Color(51, 51, 51));
        KembaliButton.setForeground(new java.awt.Color(255, 255, 255));
        KembaliButton.setText("Kembali");
        KembaliButton.setBorder(null);
        KembaliButton.setFocusPainted(false);
        KembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliButtonActionPerformed(evt);
            }
        });
        jPanel1.add(KembaliButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null,
                "Booking " + bus.maskapai + " from " + bus.keberangkatan + " to " + bus.tujuan + " berhasil");
        datahistory();
        Updatedata();
        this.removeAll();
        this.setVisible(false);
        home.UpdatePane3();
        home.revalidate();
        home.repaint();
        home.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void datahistory() {
        String data = akun.nama + ";" + bus.getClass().getSimpleName() + ";" + total() + ";" + bus.keberangkatan + "→" + bus.tujuan;
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("C:\\Users\\ASUS\\Documents\\Dev\\DataHistory.txt", true))) {
            writer.write(data);
            writer.newLine();
            System.out.println("Data pembelian berhasil disimpan.");
        } catch (IOException e) {
            System.err.println("Gagal menyimpan data pembelian: " + e.getMessage());
        }
    }

    private void Updatedata(){
        try {
            // Baca isi file
            String namafile="";
            if (bus.getClass().getSimpleName().equals("Bus")) {
                namafile="C:\\Users\\ASUS\\Documents\\Dev\\DataBus.txt";
            }
            if (bus.getClass().getSimpleName().equals("Travel")) {
                    namafile="C:\\Users\\ASUS\\Documents\\Dev\\DataTravel.txt";
            }
            if (bus.getClass().getSimpleName().equals("Pesawat")) {
                    namafile="C:\\Users\\ASUS\\Documents\\Dev\\DataPlane.txt";
            }
            
            FileReader fileReader = new FileReader(namafile);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            
            StringBuilder fileContent = new StringBuilder();
            String line;
            String temp=bus.toString();
            // Baca setiap baris dalam file
            while ((line = bufferedReader.readLine()) != null) {
                // Cek jika baris mengandung "ABCD"
                if (line.contains(bus.maskapai)&&line.contains(bus.tujuan)&&line.contains(bus.keberangkatan)&&line.contains(bus.harga)&&line.contains(String.valueOf(bus.capacity))) {
                    bus.putDataOrder(tanggal+" "+kursi);
                    System.out.println(tanggal+" "+kursi);
                    line=bus.toString(); 
                }
                // Tambahkan baris ke file content
                fileContent.append(line).append("\n");
            }
            // Tutup pembaca file
            bufferedReader.close();
            
            // Tulis ulang isi file dengan teks yang ditambahkan
            FileWriter fileWriter = new FileWriter(namafile);
            fileWriter.write(fileContent.toString());
            // Tutup file writer
            fileWriter.close();
            
            System.out.println("Teks berhasil ditambahkan ke file.");
        } catch (IOException e) {
            System.out.println("Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void KembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliButtonActionPerformed
        data.setVisible(true);
        this.setVisible(false);
        this.removeAll();
    }//GEN-LAST:event_KembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KembaliButton;
    private javax.swing.JLabel LabelTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelHarga1;
    private javax.swing.JLabel labelHarga2;
    private javax.swing.JLabel labelKeberangkatan;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelTranspo;
    private javax.swing.JLabel labelTujuan;
    // End of variables declaration//GEN-END:variables
}
