/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuliah.studycasepbo;

import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author ASUS
 */
public class HomeGui extends javax.swing.JFrame {

    /**
     * Creates new form HomeGui
     */
    LoginGui login;
    private Akun akun;
    Transportasi transport;
    ArrayList<History> historyTrans =new ArrayList<>();
    ArrayList<History> historyPeng=new ArrayList<>();

    public HomeGui(LoginGui login, Akun akun) {
        this.login = login;
        this.akun = akun;
        getHistory();
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        HotelButton = new javax.swing.JButton();
        TravelButton = new javax.swing.JButton();
        BusButton = new javax.swing.JButton();
        PlaneButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel10.setText(searchsub(historyTrans, 0, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 22, 22));
        jPanel1.setMaximumSize(new java.awt.Dimension(720, 480));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(76, 76, 76));
        panelMenu.setForeground(new java.awt.Color(102, 102, 102));
        panelMenu.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(searchsub(historyTrans, 0, 2));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel11.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(searchsub(historyTrans, 0, 1));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 5, -1, -1));

        jLabel12.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(searchsub(historyTrans, 0, 0));
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 50));

        jPanel4.setBackground(new java.awt.Color(44, 41, 41));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(searchsub(historyTrans, 1, 1));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 5, -1, -1));

        jLabel13.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(searchsub(historyTrans, 1, 0));
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel14.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(searchsub(historyTrans, 1, 2));
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 50));

        jPanel7.setBackground(new java.awt.Color(44, 41, 41));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Transportasi");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 15, -1, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 50));

        jPanel8.setBackground(new java.awt.Color(44, 41, 41));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hotel");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 15, -1, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 230, 50));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(searchsub(historyTrans, 2, 1));
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 5, -1, -1));

        jLabel16.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(searchsub(historyTrans, 2, 0));
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel17.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText(searchsub(historyTrans, 2, 2));
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 50));

        jLabel8.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("History");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 15, -1, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(searchsub(historyPeng, 0, 2));
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel19.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(searchsub(historyPeng, 0, 1));
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 5, -1, -1));

        jLabel20.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(searchsub(historyPeng, 0, 3));
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 50));

        panelMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 230, 350));

        HotelButton.setBackground(new java.awt.Color(102, 102, 102));
        HotelButton.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        HotelButton.setForeground(new java.awt.Color(255, 255, 255));
        HotelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuliah/studycasepbo/hotel.png"))); // NOI18N
        HotelButton.setText(" Penginapan");
        HotelButton.setBorder(null);
        HotelButton.setBorderPainted(false);
        HotelButton.setContentAreaFilled(false);
        HotelButton.setFocusPainted(false);
        HotelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        HotelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HotelButtonActionPerformed(evt);
            }
        });
        panelMenu.add(HotelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 190, 60));

        TravelButton.setBackground(new java.awt.Color(102, 102, 102));
        TravelButton.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        TravelButton.setForeground(new java.awt.Color(255, 255, 255));
        TravelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuliah/studycasepbo/car.png"))); // NOI18N
        TravelButton.setText("Travel");
        TravelButton.setBorder(null);
        TravelButton.setContentAreaFilled(false);
        TravelButton.setFocusPainted(false);
        TravelButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        TravelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TravelButtonActionPerformed(evt);
            }
        });
        panelMenu.add(TravelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 165, 60));

        BusButton.setBackground(new java.awt.Color(102, 102, 102));
        BusButton.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        BusButton.setForeground(new java.awt.Color(255, 255, 255));
        BusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuliah/studycasepbo/bus.png"))); // NOI18N
        BusButton.setText(" Bus");
        BusButton.setBorder(null);
        BusButton.setBorderPainted(false);
        BusButton.setContentAreaFilled(false);
        BusButton.setFocusPainted(false);
        BusButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusButtonActionPerformed(evt);
            }
        });
        panelMenu.add(BusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 140, 60));

        PlaneButton1.setBackground(new java.awt.Color(102, 102, 102));
        PlaneButton1.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        PlaneButton1.setForeground(new java.awt.Color(255, 255, 255));
        PlaneButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kuliah/studycasepbo/plane.png"))); // NOI18N
        PlaneButton1.setText(" Plane");
        PlaneButton1.setBorder(null);
        PlaneButton1.setBorderPainted(false);
        PlaneButton1.setContentAreaFilled(false);
        PlaneButton1.setFocusPainted(false);
        PlaneButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        PlaneButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaneButton1ActionPerformed(evt);
            }
        });
        panelMenu.add(PlaneButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 140, 60));

        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("KELILINK.ID");
        panelMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jPanel1.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 100, 680, 350));

        jLabel1.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome, "+akun.nama);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HotelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_HotelButtonActionPerformed
        new PenginapanGui(this, akun);
        this.setVisible(false);
    }// GEN-LAST:event_HotelButtonActionPerformed

    private void BusButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BusButtonActionPerformed
        transport = new Bus();
        openTransportasiGui();

    }// GEN-LAST:event_BusButtonActionPerformed

    private void PlaneButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PlaneButton1ActionPerformed
        transport = new Pesawat();
        openTransportasiGui();
    }// GEN-LAST:event_PlaneButton1ActionPerformed

    private void TravelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TravelButtonActionPerformed
        transport = new Travel();
        openTransportasiGui();
    }// GEN-LAST:event_TravelButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    private void openTransportasiGui() {
        new TransportasiGui(login, transport, this, akun);
        this.setVisible(false);
    }
    void getHistory(){
        historyTrans = new History().searchData(akun.nama, 1);
        historyPeng = new History().searchData(akun.nama, 2);
        System.out.println(historyTrans.size());
    }

    private String searchsub(ArrayList<History> history, int data, int flag) {
        if (history.size() > data) {
            History temp = history.get(data);
            if (flag == 0) {
                return temp.service;
            } else if (flag == 1) {
                return temp.harga;
            } else if(flag==2){
                return temp.tujuanOrHari;
            }else{
                return temp.nama;
            }
        }
        return null;
    }
    void UpdatePane3(){
        getHistory();
        jLabel12.setText(searchsub(historyTrans, 0, 0));
        jLabel12.setText(searchsub(historyTrans, 0, 0));
        jLabel11.setText(searchsub(historyTrans, 0, 1));
        jLabel7.setText(searchsub(historyTrans, 0, 2));
        jLabel13.setText(searchsub(historyTrans, 1, 0));
        jLabel14.setText(searchsub(historyTrans, 1, 2));
        jLabel9.setText(searchsub(historyTrans, 1, 1));
        jLabel16.setText(searchsub(historyTrans, 2, 0));
        jLabel15.setText(searchsub(historyTrans, 2, 1));
        jLabel17.setText(searchsub(historyTrans, 2, 2));
        jLabel20.setText(searchsub(historyPeng, 0, 3));
        jLabel19.setText(searchsub(historyPeng, 0, 1));
        jLabel18.setText(searchsub(historyPeng, 0, 2));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusButton;
    private javax.swing.JButton HotelButton;
    private javax.swing.JButton PlaneButton1;
    private javax.swing.JButton TravelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
