/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kuliah.studycasepbo;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class PenginapanGui extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    HomeGui home;
    Akun akun;
    ArrayList<Penginapan> data = new Penginapan().Searchdata();

    public PenginapanGui(HomeGui home, Akun akun) {
        this.home = home;
        this.akun = akun;
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jenisComboBox = new javax.swing.JComboBox<>();
        Kamarspin = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cariButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tanggalcheckin = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        TanggalCehckout = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        sortSpin = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(25, 22, 22));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setMinimumSize(new java.awt.Dimension(720, 480));
        jPanel3.setPreferredSize(new java.awt.Dimension(720, 480));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Penginapan");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 30, 250, 25));

        jenisComboBox.setBackground(new java.awt.Color(60, 63, 65));
        jenisComboBox.setEditable(true);
        jenisComboBox.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jenisComboBox.setForeground(new java.awt.Color(255, 255, 255));
        jenisComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Villa", "Hotel", "Hostel", "GuestHouse", "HomeStay" }));
        jenisComboBox.setBorder(null);
        jenisComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisComboBoxActionPerformed(evt);
            }
        });
        jPanel3.add(jenisComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, 25));

        Kamarspin.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        Kamarspin.setBorder(null);
        Kamarspin.setOpaque(true);
        jPanel3.add(Kamarspin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 60, 25));

        jLabel11.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kamar");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jenis");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        cariButton.setBackground(new java.awt.Color(70, 73, 75));
        cariButton.setForeground(new java.awt.Color(255, 255, 255));
        cariButton.setText("Cari");
        cariButton.setBorder(null);
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cariButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 130, 25));

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel4.setForeground(new java.awt.Color(60, 63, 65));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(jPanel4);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 620, 290));

        jLabel14.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Kamar");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Maskpai");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Jenis");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 165, -1));

        jLabel17.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Harga");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 140, -1, -1));

        Tanggalcheckin.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        Tanggalcheckin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        Tanggalcheckin.setEditor(new javax.swing.JSpinner.DateEditor(Tanggalcheckin, "dd/MM/yyyy"));
        jPanel3.add(Tanggalcheckin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, 25));

        jLabel18.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Check -in");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jButton4.setBackground(new java.awt.Color(70, 73, 75));
        jButton4.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Kembali");
        jButton4.setBorder(null);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 80, 25));

        TanggalCehckout.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        TanggalCehckout.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.DAY_OF_WEEK));
        TanggalCehckout.setEditor(new javax.swing.JSpinner.DateEditor(TanggalCehckout, "dd/MM/yyyy"));
        jPanel3.add(TanggalCehckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 100, 25));

        jLabel19.setFont(new java.awt.Font("Montserrat Medium", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Check-out");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        sortSpin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending by Capacity", "Discending by Capacity", "Ascending by Price", "Discending by Price" }));
        sortSpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortSpinActionPerformed(evt);
            }
        });
        jPanel3.add(sortSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jenisComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jenisComboBoxActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cariButtonActionPerformed
        searchAllData();
    }// GEN-LAST:event_cariButtonActionPerformed

    private void addLabel(Penginapan penginapan) {
        JPanel item = new JPanel();
        Date date1 = (Date) Tanggalcheckin.getValue();
        Date date2 = (Date) TanggalCehckout.getValue();
        LocalDate localDate1 = date1.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        LocalDate localDate2 = date2.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        DateTimeFormatter simple = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String checkin = localDate1.format(simple);
        String checkout = localDate2.format(simple);
        int days = (int) ChronoUnit.DAYS.between(localDate1, localDate2);
        int capacity = penginapan.getOrderedAt(checkin);
        String dateTemp = "";
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate date = LocalDate.parse(checkin, formatter);
        for (int i = 1; i <= days; i++) {
            LocalDate nextDate = date.plusDays(i);
            dateTemp = formatter.format(nextDate);
            int tempTanggal = penginapan.getOrderedAt(dateTemp);
            if (capacity < tempTanggal) {
                capacity = tempTanggal;
            }
        }
        item.setLayout(new BoxLayout(item, BoxLayout.X_AXIS));
        item.setBackground(new java.awt.Color(70, 73, 75));
        item.setForeground(new java.awt.Color(255, 255, 255));
        item.setMaximumSize(new java.awt.Dimension(615, 50));
        item.setMinimumSize(new java.awt.Dimension(615, 50));
        item.setPreferredSize(new java.awt.Dimension(615, 50));
        item.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        JLabel transportLabel = new JLabel("  " + penginapan.nama);
        transportLabel.setForeground(new java.awt.Color(225, 225, 225));
        transportLabel.setMaximumSize(new java.awt.Dimension(200, 20));
        transportLabel.setMinimumSize(new java.awt.Dimension(200, 20));
        transportLabel.setFont(new java.awt.Font("Montserrat Medium", 0, 12));
        JLabel Destination = new JLabel(penginapan.jenis);
        Destination.setForeground(new java.awt.Color(225, 225, 225));
        Destination.setMaximumSize(new java.awt.Dimension(100, 20));
        Destination.setFont(new java.awt.Font("Montserrat Medium", 0, 12));
        JLabel Harga = new JLabel("Rp" + penginapan.harga);
        Harga.setForeground(new java.awt.Color(225, 225, 225));
        Harga.setMaximumSize(new java.awt.Dimension(120, 20));
        Harga.setFont(new java.awt.Font("Montserrat Medium", 0, 12));
        JLabel kursi = new JLabel(String.valueOf(penginapan.kamar - capacity));
        kursi.setForeground(new java.awt.Color(225, 225, 225));
        kursi.setMaximumSize(new java.awt.Dimension(50, 20));
        kursi.setFont(new java.awt.Font("Montserrat Medium", 0, 12));
        JButton pesan = new JButton();
        pesan.setText("Pesan");
        pesan.setBackground(new java.awt.Color(70, 73, 75));
        pesan.setForeground(new java.awt.Color(255, 255, 255));

        item.add(transportLabel);
        item.add(Destination);
        item.add(Harga);
        item.add(kursi);
        jPanel4.add(item);
        if (penginapan.kamar - capacity > 0) {
            pesan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    pesanbuttonAcvtion(evt, penginapan);
                }
            });
            item.add(pesan);
        }
    }
    

    private void pesanbuttonAcvtion(java.awt.event.ActionEvent evt, Penginapan penginapan) {
        Date date1 = (Date) Tanggalcheckin.getValue();
        Date date2 = (Date) TanggalCehckout.getValue();
        LocalDate localDate1 = date1.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        LocalDate localDate2 = date2.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
        DateTimeFormatter simple = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String checkin = localDate1.format(simple);
        String checkout = localDate2.format(simple);
        int days = (int) ChronoUnit.DAYS.between(localDate1, localDate2);
        int kamar = (int) Kamarspin.getValue();
        if (days <= 0) {
            JOptionPane.showMessageDialog(null,
                    "Atur Tanggal Check-out!");
        } else {
            if (kamar > penginapan.kamar || penginapan.kamar <= 0) {
                JOptionPane.showMessageDialog(null,
                        "Kapasitas Penuh!");
            } else {
                new DataDiriTamuGui(this, home, akun, checkin, checkout, kamar, penginapan, days);
                this.setVisible(false);
            }
        }

    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        this.removeAll();
        this.setVisible(false);
        home.setVisible(true);
    }// GEN-LAST:event_jButton4ActionPerformed

    private void searchAllData() {
        jPanel4.removeAll(); // Clear previous results
        for (Penginapan temp : data) {
            if (temp.jenis.equals(jenisComboBox.getSelectedItem().toString())) {
                addLabel(temp);
            }
        }
        jPanel4.revalidate(); // Refresh the panel
        jPanel4.repaint(); // Repaint to update the
    }

    private void sortSpinActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sortSpinActionPerformed
        if (sortSpin.getSelectedItem().equals("Discending by Price")) {
            Collections.sort(data, new PDiscendingPrice());
            searchAllData();
        } else if (sortSpin.getSelectedItem().equals("Ascending by Price")) {
            Collections.sort(data, new PAscendingPrice());
            searchAllData();
        } else if (sortSpin.getSelectedItem().equals("Discending by Capacity")) {
            Collections.sort(data, new PDiscendingCapacity());
            searchAllData();
        } else {
            Collections.sort(data, new PAscendingCapacity());
            searchAllData();
        }
    }// GEN-LAST:event_sortSpinActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Kamarspin;
    private javax.swing.JSpinner TanggalCehckout;
    private javax.swing.JSpinner Tanggalcheckin;
    private javax.swing.JButton cariButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jenisComboBox;
    private javax.swing.JComboBox<String> sortSpin;
    // End of variables declaration//GEN-END:variables
}
